#!/bin/sh

if [ $# -ne 2 ]
then
  echo "grep-range: usage: start-pattern end-pattern" 1>&2
  exit 1
fi

IFS="
"

pattern_start="$1"
pattern_end="$2"
output=0

for line in `cat`
do
  echo "${line}" | grep "${pattern_start}" 1>/dev/null
  return_code=$?

  case ${return_code} in
    0) output=1 ;;
    1) ;;
    *) exit 1 ;;
  esac

  if [ ${output} -eq 1 ]
  then
    echo "${line}"
  fi

  if [ ${output} -eq 1 ]
  then
    echo "${line}" | grep "${pattern_end}" 1>/dev/null
    return_code=$?

    case ${return_code} in
      0) exit 0 ;;
      1) ;;
      *) exit 1 ;;
    esac
  fi
done
